
# GitHub Actions Workflow
# Salve este arquivo como .github/workflows/repo-analyzer.yml no seu repositório

name: Repository Analyzer Bot

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Get commit info
      id: commit
      run: |
        echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
        echo "author=$(git log -1 --pretty=%an)" >> $GITHUB_OUTPUT
        echo "diff=$(git diff HEAD~1 HEAD)" >> $GITHUB_OUTPUT

    - name: Send webhook to analyzer
      run: |
        curl -X POST "YOUR_WEBHOOK_URL_HERE" \
          -H "Content-Type: application/json" \
          -d '{
            "repository": "${{ github.repository }}",
            "commit_sha": "${{ steps.commit.outputs.sha }}",
            "commit_message": "${{ steps.commit.outputs.message }}",
            "author": "${{ steps.commit.outputs.author }}",
            "branch": "${{ github.ref_name }}",
            "diff": "${{ steps.commit.outputs.diff }}"
          }'
