
# Salve este arquivo como .github/workflows/repo-analyzer.yml no seu repositório
name: Repo Analyzer Bot

on:
  push:
    branches: [ main, master, develop ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Busca o commit anterior para gerar o diff
        fetch-depth: 2

    - name: Prepare Commit Data
      id: commit_data
      run: |
        # Usamos jq para construir um JSON seguro, evitando problemas com caracteres especiais
        COMMIT_MESSAGE=$(git log -1 --pretty=%B | jq -sR .)
        COMMIT_DIFF=$(git diff HEAD~1 HEAD | jq -sR .)
        
        JSON_PAYLOAD=$(cat <<EOF
        {
          "repository": "${{ github.repository }}",
          "commit_sha": "${{ github.sha }}",
          "commit_url": "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}",
          "commit_message": $COMMIT_MESSAGE,
          "author": "${{ github.actor }}",
          "branch": "${{ github.ref_name }}",
          "diff": $DIFF_PAYLOAD
        }
        EOF
        )
        echo "payload=$(echo $JSON_PAYLOAD | jq -c .)" >> $GITHUB_OUTPUT

    - name: Send Webhook to Analyzer
      uses: distributhor/workflow-webhook@v3
      env:
        webhook_url: ${{ secrets.ANALYZER_WEBHOOK_URL }} # Crie este secret no GitHub
        webhook_secret: "" # Opcional, se configurado no backend
        data: '${{ steps.commit_data.outputs.payload }}'
